version: '3.8'

services:
  crud:
    container_name: td-springboot
    build:
      context: ./springboot-app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://database:5432/mydb
      - DATABASE_USER=myuser
      - DATABASE_PASSWORD=mypassword
    depends_on:
      - database

  database:
    container_name: postgres-database
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: ghcr.io/shyim/adminerevo:latest
    restart: always
    ports:
      - 9000:8080
    depends_on:
      - database

volumes:
  db-data: