apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: talento-digital
spec:
  selector:
    app: postgres
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  type: ClusterIP